# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ec7610ec9145c79f214a163b6c38c5577f52c64d49d10d90b05087bb6aaa454e6a97e68f5d96f4e18d8c872f494c6c9c2415b771d5a67a232a8289be4f7afd5

test:
  secret_key_base: 41625cff135c515a0c9f056a8765820751ba905cc18fd287421587aa9f85eae23621ab829a753aff9a1117beba0794ddc6c9e4186d88b798202c9e7f0ba604a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
